# Generated by Django 3.2.8 on 2022-01-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20220103_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='branch',
        ),
        migrations.AddField(
            model_name='notes',
            name='receiverType',
            field=models.CharField(default='null', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='batch',
            field=models.CharField(default='null', max_length=4),
        ),
        migrations.AddField(
            model_name='person',
            name='rollno',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='section',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='notes',
            name='fileType',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='sendTo',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploadDate',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
